### ISSUE TITLE
Test users routine

### ISSUE THREAD

**Issue by israellevin** [paket-core/funder#17]
When running in a debug environment, we would like to have a few "automatic" users:
1. Courier user, which checks to see if he has any packages waiting for him to courier, and automatically picks them up and sends change_location every once in a while.
2. Recipient user, which checks if any packages meant for him are not in the hands of the Launcher and are over an hour old, and automatically accepts them.
3. Launcher user, which launches a new package every time he is not the custodian of any existing packages.

We also need a routine to create those users if they do not exist.

Keys will be held in env vars, as usual.

**Comment by israellevin** [comment]
@yaroslavr-itd , this is now high priority (following testnet reset). Also, please have a look at our kanban (https://github.com/orgs/paket-core/projects/1) and update things.

**Comment by yaroslavr-itd** [comment]
Started at [25f7574](https://github.com/paket-core/funder/commit/25f75742a0a60f62ae2d0bd58ec2f1b4ee9011a5), finished at [c4e6b8b](https://github.com/paket-core/funder/commit/c4e6b8b35a0dff32a7aa3bd7b2415f096fc953fa)
