### ISSUE TITLE
Use fuzzy KYC/AML check

### ISSUE THREAD

**Issue by israellevin** [paket-core/funder#2]

**Comment by israellevin** [comment]
This is waiting for some small clarification for questions @yaroslavr-itd will add, but generally, we should remove testing of phone and address and just use full name and we are done.

**Comment by yaroslavr-itd** [comment]
Fixed in commit #b044f3c5499f4fa9ab94982b35dbbe1099f995f8 (_basic-kyc-enhancement_ branch)
No more phone and address testing in basic_kyc.
Tests still starts only after providing full info about user: name, phone, address

**Comment by yaroslavr-itd** [comment]
The general question is: can we use Oren's code for checking not only names, but addresses, for example.
Specific questions are related to algorithm of checking:
- why for _fuzzy_score_ we need to multiply partial_ratio by 0.95 and divide ratio by 5. What that magic numbers actually are?
- why _final_score_ is _top_score_ squared?

**Comment by israellevin** [comment]
The answer to the general question is "not at this time". We are not using the list to check for anything but names.

As for specific questions:

- exact match score can cause a lot of false negatives (Yarik is not an exact match for Yarick), so we need to tone it down. We should have constants EXACT_MATCH_WEIGHT and FUZZY_MATCH_WEIGHT and use them.
-  This reduces false positives. Makes the distinction between good scores and bad scores more distinct.

Again, it's all numbers that were tweaked until we got acceptable results. Not perfect, but sufficient for now.
