### ISSUE TITLE
Increase fund amount

### ISSUE THREAD

**Issue by yaroslavr-itd** [paket-core/funder#29]
Starting balance for new account should be increased to 10 XLM.

**Comment by yaroslavr-itd** [comment]
Done in `manager` repo, [f7a073a](https://github.com/paket-core/manager/commit/f7a073a68bf2091326eccfbfa206ab04e213f35c)

**Comment by israellevin** [comment]
@yaroslavr-itd , this solved our problem, correct?

**Comment by yaroslavr-itd** [comment]
@israellevin yes. Because with previous starting balance user had been able to create only one escrow for package.
