### ISSUE TITLE
Bad key when trying to generate bitcoin address

### ISSUE THREAD

**Issue by israellevin** [paket-core/funder#39]
On the app we get the error: incorrect network. Bitcoin Test Net expects a byt prefix of 70617039, but you supplied b'\x04\x88\xb2\x1e'.

**Comment by yaroslavr-itd** [comment]
This happens because of using mainnet keys on testnet.

HOW TO FIX
In some reason there is mainnet XPUB key provided in manager. Need to replace it to testnet XPUB (for example, tpubD6NzVbkrYhZ4XMSG7EWChwJXwfByid9TdZRVaej1rpDTHV3WamyuApceF5DDZXetx8kbH82NouoazYqPeCEZWWeXHZ1do5LBCe5xMcZYeGe)

**Comment by yaroslavr-itd** [comment]
@israellevin review, please
