### ISSUE TITLE
Do not accept valid pubkeys as call-signs

### ISSUE THREAD

**Issue by israellevin** [paket-core/funder#7]
This is a design bug. Currently it is possible to have a valid pubkey as a call-sign, in which case it is unclear how the mobile app should behave. Issue an error when trying to create a user with a call-sign that is a valid pubkey. Use webserver's checkers mechanism. Something like:  `KWARGS_CHECKERS_AND_FIXERS['call_sign'] = lambda k, c: not check_pubkey(k, c)`.

**Comment by yaroslavr-itd** [comment]
Fixed in [9aab4ac6a1a9f72a709f897d3a144be8ae69f7e4](https://github.com/paket-core/funder/commit/9aab4ac6a1a9f72a709f897d3a144be8ae69f7e4) commit.
